### ISSUE TITLE
Update for newer versions of WordPress

### ISSUE THREAD

**Issue by vincentml** [boonebgorges/unconfirmed#21]
There are reports that this plugin does not work with more recent versions of WordPress.

https://wordpress.org/support/topic/not-working-with-4-6/

Can this plugin be updated to be compatible with the current version of WordPress?

**Comment by boonebgorges** [comment]
I'm running it on a number of sites and it's working fine.

If you run into a specific issue, please share the details here.

**Comment by DJaeger** [comment]
I think you should at least update the last tested version to not let the users think its outdated.

**Comment by boonebgorges** [comment]
@DJaeger Yes, good idea. I've bumped the tested version on wordpress.org.

**Comment by dimalif** [comment]
You say at WP.org that it works with 4.9.11 but it doesn't.

**Comment by boonebgorges** [comment]
@dimalif Can you specify the problem that you're having?

**Comment by dimalif** [comment]
Sure i can. I use 4.9.12 (as of today's update) and simply your plugin shows zero Unconfirmed. No errors anywhere, empty debug log. 

I run WP with PHP 7.2 and MariaDB 10x. No Multisite.

Some people told me that your plugin works ONLY with multisite but i don't find that information anywhere at WP plugin's page.

**Comment by boonebgorges** [comment]
Thanks for the details. I'll try to find some time to reproduce this setup and see if I can pinpoint the problem.
